### ISSUE TITLE
Needs a license

### ISSUE THREAD

**Issue by RichardLitt** [ethereum/solidity-test-bytecode#1]
This repository is unlicensed. While it's not probable that this will cause an issue with anyone, it is an easy issue to fix. I'd be happy to throw an MIT license into a PR.

**Comment by chriseth** [comment]
If you want, you can add MIT license headers to the scripts, I would be a little uneasy to license the repository as a whole because it mostly consists of generated binary files.

**Comment by igotthis2020** [comment]
Thank you Chriseth, i am on it.
